# Generated by Django 4.2.14 on 2024-08-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, max_length=200, null=True)),
                ('district_name', models.CharField(blank=True, max_length=200, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('area_cultivated', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CropDataJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_data', models.JSONField(blank=True, null=True)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('process_id', models.CharField(blank=True, max_length=255, null=True)),
                ('added_time', models.CharField(blank=True, max_length=255, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_code', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('english_name', models.CharField(blank=True, max_length=200, null=True)),
                ('local_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('process_id', models.CharField(blank=True, null=True)),
                ('crop_type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_generating', models.BooleanField(default=False)),
                ('is_extracting', models.BooleanField(default=False)),
                ('is_aggregating', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_code', models.IntegerField(default=11, primary_key=True, serialize=False)),
                ('english_name', models.CharField(blank=True, max_length=300, null=True)),
                ('local_name', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('subdistrict_code', models.IntegerField(default=111, primary_key=True, serialize=False)),
                ('english_name', models.CharField(blank=True, max_length=200, null=True)),
                ('local_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.district')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.state')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_code', models.IntegerField(default=12, primary_key=True, serialize=False)),
                ('english_name', models.CharField(blank=True, max_length=200, null=True)),
                ('local_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.district')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.state')),
                ('subdistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.subdistrict')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.state'),
        ),
        migrations.CreateModel(
            name='CropDetails',
            fields=[
                ('unique_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('area_cultivated', models.IntegerField(blank=True, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('yeild_perhectare', models.IntegerField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=50, null=True)),
                ('irrigation_method', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_min', models.IntegerField(blank=True, null=True)),
                ('temp_max', models.IntegerField(blank=True, null=True)),
                ('temp_avg', models.IntegerField(blank=True, null=True)),
                ('rainfall_total', models.IntegerField(blank=True, null=True)),
                ('rainfall_rainy_days', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('fertilizer_NPK_kg', models.IntegerField(blank=True, null=True)),
                ('fertilizer_COMPOST_kg', models.IntegerField(blank=True, null=True)),
                ('pesticide_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pesticide_quantity_l', models.IntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.district')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.state')),
                ('subdistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.subdistrict')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.village')),
            ],
        ),
    ]
