# Generated by Django 4.2.14 on 2024-07-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropname', models.CharField(max_length=200)),
            ],
        ),
        
        migrations.CreateModel(
            name='Cropdatajson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropdata', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('districtcode', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('englishname', models.CharField(blank=True, max_length=200, null=True)),
                ('localname', models.CharField(blank=True, max_length=200, null=True)),
                ('districtcreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('districtupdated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('statecode', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('englishname', models.CharField(blank=True, max_length=300, null=True)),
                ('localname', models.CharField(blank=True, max_length=300, null=True)),
                ('statecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('stateupdated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('subdistrictcode', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('englishname', models.CharField(blank=True, max_length=200, null=True)),
                ('localname', models.CharField(blank=True, max_length=200, null=True)),
                ('subdistrictcreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('subdistrictupdated', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.IntegerField(blank=True, default=0, null=True)),
                ('district', models.ForeignKey(blank=True, default=1121, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.district')),
            ],
        ),
       
        migrations.CreateModel(
            name='Village',
            fields=[
                ('villagecode', models.IntegerField(default=3, primary_key=True, serialize=False)),
                ('englishname', models.CharField(blank=True, max_length=200, null=True)),
                ('localname', models.CharField(blank=True, max_length=200, null=True)),
                ('villagecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('villageupdated', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.district')),
                ('state', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.state')),
                ('subdistrict', models.ForeignKey(blank=True, default=12342, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.subdistrict')),
            ],
        ),
        
        
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.state'),
        ),
       
    ]
