# Generated by Django 4.2.14 on 2024-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
