# Generated by Django 4.2.14 on 2024-08-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0002_alter_state_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
