# Generated by Django 4.2.14 on 2024-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0002_cropdatajson_added_cropdatajson_district_cropdetails_and_more'),
    ]

    operations = [
        
    ]
