# Generated by Django 4.2.14 on 2024-08-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0003_cropdatajson_added_cropdatajson_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggridata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('crop', models.CharField(blank=True, max_length=100, null=True)),
                ('area_cultivated', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cropdatajson',
            name='added',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cropdatajson',
            name='district',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
