# Generated by Django 4.2.14 on 2024-08-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0003_alter_district_district_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdistrict',
            name='subdistrict_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
