# Generated by Django 4.2.14 on 2024-08-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0004_alter_subdistrict_subdistrict_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='village_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
