# Generated by Django 4.2.14 on 2024-08-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0004_aggridata_cropdatajson_added_cropdatajson_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdatajson',
            name='process_id',
            field=models.CharField(blank=True, null=tuple),
            preserve_default=tuple,
        ),
    ]
