# Generated by Django 4.2.14 on 2024-08-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0005_alter_village_village_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdetails',
            name='process_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processstatus',
            name='process_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
