# Generated by Django 4.2.14 on 2024-08-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0006_cropdatajson_added_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdatajson',
            name='corp_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
