# Generated by Django 4.2.14 on 2024-08-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0007_cropdatajson_corp_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropdatajson',
            old_name='corp_type',
            new_name='crop_type',
        ),
    ]
