# Generated by Django 4.2.14 on 2024-08-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0007_alter_cropdatajson_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdetails',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.district'),
        ),
        migrations.AlterField(
            model_name='cropdetails',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.state'),
        ),
        migrations.AlterField(
            model_name='cropdetails',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.subdistrict'),
        ),
        migrations.AlterField(
            model_name='cropdetails',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.village'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.state'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.district'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.state'),
        ),
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.district'),
        ),
        migrations.AlterField(
            model_name='village',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.state'),
        ),
        migrations.AlterField(
            model_name='village',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fetch.subdistrict'),
        ),
    ]
