# Generated by Django 4.2.14 on 2024-08-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0008_rename_corp_type_cropdatajson_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdatajson',
            name='added_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
