# Generated by Django 4.2.14 on 2024-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0012_sample_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
