# Generated by Django 4.2.14 on 2024-08-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0013_delete_sample_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdatajson',
            name='added',
        ),
        migrations.AddField(
            model_name='cropdatajson',
            name='is_aggregation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropdatajson',
            name='is_extraction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropdatajson',
            name='is_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropdatajson',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cropdatajson',
            name='added_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cropdatajson',
            name='crop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cropdatajson',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cropdatajson',
            name='process_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
