# Generated by Django 4.2.14 on 2024-08-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0015_process_status_delete_datagenerationstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_status',
            name='status',
        ),
    ]
