# Generated by Django 4.2.14 on 2024-08-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0016_remove_process_status_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdatajson',
            name='is_aggregation',
        ),
        migrations.RemoveField(
            model_name='cropdatajson',
            name='is_extraction',
        ),
        migrations.RemoveField(
            model_name='cropdatajson',
            name='is_failed',
        ),
        migrations.RemoveField(
            model_name='cropdatajson',
            name='is_generation',
        ),
        migrations.AddField(
            model_name='process_status',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
